### ISSUE TITLE
Error when creating symlink

### ISSUE THREAD

**Issue by AnhChienVu** [KrinsKumar/Scrappy#2]
I am having error when try to create a symlink that connect your command.js to the bin folder that you want to use the application's name to run. I did a research and saw that the ln command is used on Unix-like system, so I guess you are using Mac. Because I am using Windows OS, so if I follow your README file, I couldn't install the app. So I think you should add instructions for Windows User as well.
I will create a new branch and work a bit on setting up the symlink that can be a bit easier to set up the app.

**Comment by KrinsKumar** [comment]
Great work, than you
