### ISSUE TITLE
New Feature: Support using a TOML "dotfile" config file in the user's homedir

### ISSUE THREAD

**Issue by uday-rana** [KrinsKumar/Scrappy#8]
## Description

Users want to be able to specify all of their options to your tool in a [TOML](https://toml.io/en/) formatted configuration file that they store in their home directory, instead of having to pass them all as command line arguments every time. For example, consider the following config file, `~/.your-toolname-config.toml`:

```
model = "gpt-4o"
api_key = "sk-...."
# etc...
```
Then, when the user runs your tool, it will search for a config file in the home dir and use those values. Or, if the user specifies values via args, those will override the default ones in the config.

NOTE: there are [many open source TOML implementations](https://github.com/toml-lang/toml/wiki#implementations) you can use to parse the config file. Don't write the parser yourself, pick a well maintained library instead.

## Requirements

1. The tool should look in the home dir for a "dotfile" TOML config (i.e., a file that starts with . and contains default options in TOML format)
2. If the file is missing, ignore this
3. If the file is present but can't be parsed as TOML, exit with an appropriate error message.
4. If the file exists and no command line args override any values, the values in the config file should be used (e.g., use the model in the config)
5. The program should ignore any options in the config file it doesn't recognize.

**Comment by uday-rana** [comment]
Done, waiting for review and merge

**Comment by KrinsKumar** [comment]
great work!!
